<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model" nsURI="model.ecore" nsPrefix="model">
  <eClassifiers xsi:type="ecore:EDataType" name="String" instanceClassName="java.lang.String"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Boolean" instanceClassName="java.lang.Boolean"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Double" instanceClassName="java.lang.Double"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Integer" instanceClassName="java.lang.Integer"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EList" instanceClassName="org.eclipse.emf.common.util.EList"/>
  <eClassifiers xsi:type="ecore:EClass" name="FactoryModel">
    <eOperations name="cargar" eType="#//FactoryModel">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="ModelPackage modelPackage = ModelPackage.eINSTANCE; &#xA; FactoryModel factoryModel = null;&#xA;org.eclipse.emf.common.util.URI uri = org.eclipse.emf.common.util.URI.createURI(&quot;platform:/resource/dataformmodel/persistencia/dataform.model&quot;);&#xA;org.eclipse.emf.ecore.resource.ResourceSet resourceSet= new org.eclipse.emf.ecore.resource.impl.ResourceSetImpl();&#xA;org.eclipse.emf.ecore.resource.Resource resource = resourceSet.createResource(uri);&#xA;try {&#xA;resource.load(java.util.Collections.EMPTY_MAP);&#xA;factoryModel = (FactoryModel) resource.getContents().get(0);&#xA;} catch (java.io.IOException e) {&#xA;e.printStackTrace();&#xA;}&#xA;return factoryModel;&#xA;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="salvar">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="FactoryModel factoryModel = this;&#xA; org.eclipse.emf.common.util.URI uri = org.eclipse.emf.common.util.URI.createURI(&quot;platform:/resource/dataformmodel/persistencia/dataform.model&quot;);&#xA;org.eclipse.emf.ecore.resource.ResourceSet resourceSet= new org.eclipse.emf.ecore.resource.impl.ResourceSetImpl();&#xA;org.eclipse.emf.ecore.resource.Resource resource = resourceSet.createResource(uri);&#xA;resource.getContents().add(factoryModel);&#xA;try {&#xA;resource.save(java.util.Collections.EMPTY_MAP);&#xA;} catch (java.io.IOException e) {&#xA;e.printStackTrace();&#xA;}&#xA;return;&#xA;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="theUIManager" lowerBound="1"
        eType="#//uimanager/UIManager" containment="true" eOpposite="#//uimanager/UIManager/ownedByFactoryModel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="theDomain" lowerBound="1"
        eType="#//domain/Domain" containment="true" eOpposite="#//domain/Domain/ownedByFactoryModel"/>
  </eClassifiers>
  <eSubpackages name="uimanager" nsURI="model/uimanager.ecore" nsPrefix="model.uimanager">
    <eClassifiers xsi:type="ecore:EClass" name="UIManager">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedByFactoryModel"
          lowerBound="1" eType="#//FactoryModel" eOpposite="#//FactoryModel/theUIManager"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="theVentanaMemorandoViewModel"
          lowerBound="1" eType="#//uimanager/VentanaMemorandoViewModel" containment="true"
          eOpposite="#//uimanager/VentanaMemorandoViewModel/theUiManager"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="theDomain" lowerBound="1"
          eType="#//domain/Domain" eOpposite="#//domain/Domain/theUIManager"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VentanaMemorandoViewModel">
      <eStructuralFeatures xsi:type="ecore:EReference" name="theUiManager" lowerBound="1"
          eType="#//uimanager/UIManager" eOpposite="#//uimanager/UIManager/theVentanaMemorandoViewModel"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="theContenedorInformacionMemorando"
          lowerBound="1" eType="#//uimanager/ContenedorInformacionMemorando" containment="true"
          eOpposite="#//uimanager/ContenedorInformacionMemorando/ownedByVentanaMemorandoViewModel"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="theContenedorMemorando"
          lowerBound="1" eType="#//uimanager/ContenedorMemorando" containment="true"
          eOpposite="#//uimanager/ContenedorMemorando/ownedByVentanaMemorandoViewModel"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ContenedorInformacionMemorando">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedByVentanaMemorandoViewModel"
          lowerBound="1" eType="#//uimanager/VentanaMemorandoViewModel" eOpposite="#//uimanager/VentanaMemorandoViewModel/theContenedorInformacionMemorando"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="unidado" eType="#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="remitente" eType="#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fecha" eType="#//String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ContenedorMemorando">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedByVentanaMemorandoViewModel"
          lowerBound="1" eType="#//uimanager/VentanaMemorandoViewModel" eOpposite="#//uimanager/VentanaMemorandoViewModel/theContenedorMemorando"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="listMemorando" upperBound="-1"
          eType="#//uimanager/MemorandoViewModel" containment="true" eOpposite="#//uimanager/MemorandoViewModel/ownedByMemorando"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MemorandoViewModel">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedByMemorando" lowerBound="1"
          eType="#//uimanager/ContenedorMemorando" eOpposite="#//uimanager/ContenedorMemorando/listMemorando"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="tipo" eType="#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="hora" eType="#//String"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="domain" nsURI="model/domain.ecore" nsPrefix="model.domain">
    <eClassifiers xsi:type="ecore:EClass" name="Domain">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedByFactoryModel"
          lowerBound="1" eType="#//FactoryModel" eOpposite="#//FactoryModel/theDomain"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="theUIManager" lowerBound="1"
          eType="#//uimanager/UIManager" eOpposite="#//uimanager/UIManager/theDomain"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="datatypes" nsURI="model/.datatypes.ecore" nsPrefix="model.datatypes">
    <eClassifiers xsi:type="ecore:EDataType" name="EList" instanceClassName="org.eclipse.emf.common.util.EList"/>
  </eSubpackages>
</ecore:EPackage>
