/**
 */
package gestionmodelosconsultas.sysinfo.data.docmgt.provider;

import gestionmodelosconsultas.sysinfo.data.docmgt.util.DocmgtAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class DocmgtItemProviderAdapterFactory extends DocmgtAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public DocmgtItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link gestionmodelosconsultas.sysinfo.data.docmgt.Documento} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DocumentoItemProvider documentoItemProvider;

	/**
	 * This creates an adapter for a {@link gestionmodelosconsultas.sysinfo.data.docmgt.Documento}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDocumentoAdapter() {
		if (documentoItemProvider == null) {
			documentoItemProvider = new DocumentoItemProvider(this);
		}

		return documentoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link gestionmodelosconsultas.sysinfo.data.docmgt.Plantilla} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PlantillaItemProvider plantillaItemProvider;

	/**
	 * This creates an adapter for a {@link gestionmodelosconsultas.sysinfo.data.docmgt.Plantilla}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPlantillaAdapter() {
		if (plantillaItemProvider == null) {
			plantillaItemProvider = new PlantillaItemProvider(this);
		}

		return plantillaItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link gestionmodelosconsultas.sysinfo.data.docmgt.Guia} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GuiaItemProvider guiaItemProvider;

	/**
	 * This creates an adapter for a {@link gestionmodelosconsultas.sysinfo.data.docmgt.Guia}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGuiaAdapter() {
		if (guiaItemProvider == null) {
			guiaItemProvider = new GuiaItemProvider(this);
		}

		return guiaItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link gestionmodelosconsultas.sysinfo.data.docmgt.ListaChequeo} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ListaChequeoItemProvider listaChequeoItemProvider;

	/**
	 * This creates an adapter for a {@link gestionmodelosconsultas.sysinfo.data.docmgt.ListaChequeo}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createListaChequeoAdapter() {
		if (listaChequeoItemProvider == null) {
			listaChequeoItemProvider = new ListaChequeoItemProvider(this);
		}

		return listaChequeoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link gestionmodelosconsultas.sysinfo.data.docmgt.Contenido} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ContenidoItemProvider contenidoItemProvider;

	/**
	 * This creates an adapter for a {@link gestionmodelosconsultas.sysinfo.data.docmgt.Contenido}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createContenidoAdapter() {
		if (contenidoItemProvider == null) {
			contenidoItemProvider = new ContenidoItemProvider(this);
		}

		return contenidoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link gestionmodelosconsultas.sysinfo.data.docmgt.TipoDocumento} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TipoDocumentoItemProvider tipoDocumentoItemProvider;

	/**
	 * This creates an adapter for a {@link gestionmodelosconsultas.sysinfo.data.docmgt.TipoDocumento}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTipoDocumentoAdapter() {
		if (tipoDocumentoItemProvider == null) {
			tipoDocumentoItemProvider = new TipoDocumentoItemProvider(this);
		}

		return tipoDocumentoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link gestionmodelosconsultas.sysinfo.data.docmgt.Copia} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CopiaItemProvider copiaItemProvider;

	/**
	 * This creates an adapter for a {@link gestionmodelosconsultas.sysinfo.data.docmgt.Copia}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCopiaAdapter() {
		if (copiaItemProvider == null) {
			copiaItemProvider = new CopiaItemProvider(this);
		}

		return copiaItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link gestionmodelosconsultas.sysinfo.data.docmgt.Version} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected VersionItemProvider versionItemProvider;

	/**
	 * This creates an adapter for a {@link gestionmodelosconsultas.sysinfo.data.docmgt.Version}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createVersionAdapter() {
		if (versionItemProvider == null) {
			versionItemProvider = new VersionItemProvider(this);
		}

		return versionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link gestionmodelosconsultas.sysinfo.data.docmgt.IndexEntry} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IndexEntryItemProvider indexEntryItemProvider;

	/**
	 * This creates an adapter for a {@link gestionmodelosconsultas.sysinfo.data.docmgt.IndexEntry}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIndexEntryAdapter() {
		if (indexEntryItemProvider == null) {
			indexEntryItemProvider = new IndexEntryItemProvider(this);
		}

		return indexEntryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link gestionmodelosconsultas.sysinfo.data.docmgt.PalabraClave} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PalabraClaveItemProvider palabraClaveItemProvider;

	/**
	 * This creates an adapter for a {@link gestionmodelosconsultas.sysinfo.data.docmgt.PalabraClave}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPalabraClaveAdapter() {
		if (palabraClaveItemProvider == null) {
			palabraClaveItemProvider = new PalabraClaveItemProvider(this);
		}

		return palabraClaveItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link gestionmodelosconsultas.sysinfo.data.docmgt.Item} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ItemItemProvider itemItemProvider;

	/**
	 * This creates an adapter for a {@link gestionmodelosconsultas.sysinfo.data.docmgt.Item}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createItemAdapter() {
		if (itemItemProvider == null) {
			itemItemProvider = new ItemItemProvider(this);
		}

		return itemItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link gestionmodelosconsultas.sysinfo.data.docmgt.Baseline} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BaselineItemProvider baselineItemProvider;

	/**
	 * This creates an adapter for a {@link gestionmodelosconsultas.sysinfo.data.docmgt.Baseline}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBaselineAdapter() {
		if (baselineItemProvider == null) {
			baselineItemProvider = new BaselineItemProvider(this);
		}

		return baselineItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link gestionmodelosconsultas.sysinfo.data.docmgt.Indice} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IndiceItemProvider indiceItemProvider;

	/**
	 * This creates an adapter for a {@link gestionmodelosconsultas.sysinfo.data.docmgt.Indice}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIndiceAdapter() {
		if (indiceItemProvider == null) {
			indiceItemProvider = new IndiceItemProvider(this);
		}

		return indiceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link gestionmodelosconsultas.sysinfo.data.docmgt.Producto} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ProductoItemProvider productoItemProvider;

	/**
	 * This creates an adapter for a {@link gestionmodelosconsultas.sysinfo.data.docmgt.Producto}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createProductoAdapter() {
		if (productoItemProvider == null) {
			productoItemProvider = new ProductoItemProvider(this);
		}

		return productoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link gestionmodelosconsultas.sysinfo.data.docmgt.Mensaje} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MensajeItemProvider mensajeItemProvider;

	/**
	 * This creates an adapter for a {@link gestionmodelosconsultas.sysinfo.data.docmgt.Mensaje}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMensajeAdapter() {
		if (mensajeItemProvider == null) {
			mensajeItemProvider = new MensajeItemProvider(this);
		}

		return mensajeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link gestionmodelosconsultas.sysinfo.data.docmgt.Glosario} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GlosarioItemProvider glosarioItemProvider;

	/**
	 * This creates an adapter for a {@link gestionmodelosconsultas.sysinfo.data.docmgt.Glosario}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGlosarioAdapter() {
		if (glosarioItemProvider == null) {
			glosarioItemProvider = new GlosarioItemProvider(this);
		}

		return glosarioItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link gestionmodelosconsultas.sysinfo.data.docmgt.Libreria} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LibreriaItemProvider libreriaItemProvider;

	/**
	 * This creates an adapter for a {@link gestionmodelosconsultas.sysinfo.data.docmgt.Libreria}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLibreriaAdapter() {
		if (libreriaItemProvider == null) {
			libreriaItemProvider = new LibreriaItemProvider(this);
		}

		return libreriaItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link gestionmodelosconsultas.sysinfo.data.docmgt.Distribucion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DistribucionItemProvider distribucionItemProvider;

	/**
	 * This creates an adapter for a {@link gestionmodelosconsultas.sysinfo.data.docmgt.Distribucion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDistribucionAdapter() {
		if (distribucionItemProvider == null) {
			distribucionItemProvider = new DistribucionItemProvider(this);
		}

		return distribucionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link gestionmodelosconsultas.sysinfo.data.docmgt.Orientacion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OrientacionItemProvider orientacionItemProvider;

	/**
	 * This creates an adapter for a {@link gestionmodelosconsultas.sysinfo.data.docmgt.Orientacion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOrientacionAdapter() {
		if (orientacionItemProvider == null) {
			orientacionItemProvider = new OrientacionItemProvider(this);
		}

		return orientacionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link gestionmodelosconsultas.sysinfo.data.docmgt.Doc} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DocItemProvider docItemProvider;

	/**
	 * This creates an adapter for a {@link gestionmodelosconsultas.sysinfo.data.docmgt.Doc}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDocAdapter() {
		if (docItemProvider == null) {
			docItemProvider = new DocItemProvider(this);
		}

		return docItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link gestionmodelosconsultas.sysinfo.data.docmgt.Copias} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CopiasItemProvider copiasItemProvider;

	/**
	 * This creates an adapter for a {@link gestionmodelosconsultas.sysinfo.data.docmgt.Copias}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCopiasAdapter() {
		if (copiasItemProvider == null) {
			copiasItemProvider = new CopiasItemProvider(this);
		}

		return copiasItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (documentoItemProvider != null) documentoItemProvider.dispose();
		if (plantillaItemProvider != null) plantillaItemProvider.dispose();
		if (guiaItemProvider != null) guiaItemProvider.dispose();
		if (listaChequeoItemProvider != null) listaChequeoItemProvider.dispose();
		if (contenidoItemProvider != null) contenidoItemProvider.dispose();
		if (tipoDocumentoItemProvider != null) tipoDocumentoItemProvider.dispose();
		if (copiaItemProvider != null) copiaItemProvider.dispose();
		if (versionItemProvider != null) versionItemProvider.dispose();
		if (indexEntryItemProvider != null) indexEntryItemProvider.dispose();
		if (palabraClaveItemProvider != null) palabraClaveItemProvider.dispose();
		if (itemItemProvider != null) itemItemProvider.dispose();
		if (baselineItemProvider != null) baselineItemProvider.dispose();
		if (indiceItemProvider != null) indiceItemProvider.dispose();
		if (productoItemProvider != null) productoItemProvider.dispose();
		if (mensajeItemProvider != null) mensajeItemProvider.dispose();
		if (glosarioItemProvider != null) glosarioItemProvider.dispose();
		if (libreriaItemProvider != null) libreriaItemProvider.dispose();
		if (distribucionItemProvider != null) distribucionItemProvider.dispose();
		if (orientacionItemProvider != null) orientacionItemProvider.dispose();
		if (docItemProvider != null) docItemProvider.dispose();
		if (copiasItemProvider != null) copiasItemProvider.dispose();
	}

}
